# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGG-31Zx6lunuf1T7260rkqrnrSWQExU
"""

# read_file.py

import pandas as pd

def read_dataset(file_path):
    """
    Read the dataset CSV and return a pandas DataFrame.
    """
    try:
        df = pd.read_csv(file_path)
        print("Dataset loaded successfully.")
        return df
    except Exception as e:
        print("Error loading dataset:", e)
        return None

if __name__ == "__main__":
    data = read_dataset("dataset.csv")
    if data is not None:
        print(data.head())