# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PV9tLJ8seyH4mvlRt83Xv0ExHAAtYV4l
"""

# source_data.py

import pandas as pd

def get_sample_data():
    """
    Simulates sample data extraction from social media APIs.
    Replace this with actual API integration using Tweepy, PRAW, etc.
    """
    data = {
        "post_id": [1, 2, 3],
        "platform": ["Twitter", "Reddit", "YouTube"],
        "content": [
            "I love this product! It's amazing.",
            "This is the worst experience I've had.",
            "Meh, it was okay. Nothing special."
        ],
        "label": ["positive", "negative", "neutral"]
    }
    df = pd.DataFrame(data)
    df.to_csv("dataset.csv", index=False)
    print("Sample dataset created as dataset.csv")

if __name__ == "__main__":
    get_sample_data()